<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body{font-family:DejaVu Sans,sans-serif;font-size:12px;color:#1e293b;margin:0;padding:20px;}
h1{font-size:20px;color:#1d4ed8;margin-bottom:4px;}
.sub{color:#64748b;font-size:12px;margin-bottom:20px;}
.stats{display:flex;gap:20px;margin-bottom:20px;}
.stat{flex:1;border:1px solid #e2e8f0;border-radius:8px;padding:12px;text-align:center;}
.stat-label{color:#64748b;font-size:10px;margin-bottom:4px;}
.stat-value{font-size:16px;font-weight:700;}
.income{color:#16a34a;}.expense{color:#dc2626;}.net{color:#2563eb;}
table{width:100%;border-collapse:collapse;font-size:11px;}
th{background:#f1f5f9;padding:8px;text-align:left;border:1px solid #e2e8f0;font-weight:600;}
td{padding:7px 8px;border:1px solid #e2e8f0;}
tr:nth-child(even) td{background:#f8fafc;}
.footer{margin-top:20px;color:#94a3b8;font-size:10px;text-align:center;}
</style>
</head>
<body>
<h1>💰 Laporan Keuangan</h1>
<p class="sub">{{ $user->name }} · {{ $startDate }} s/d {{ $endDate }}</p>

<div class="stats">
    <div class="stat"><div class="stat-label">Total Pemasukan</div><div class="stat-value income">Rp {{ number_format($totalIncome,0,',','.') }}</div></div>
    <div class="stat"><div class="stat-label">Total Pengeluaran</div><div class="stat-value expense">Rp {{ number_format($totalExpense,0,',','.') }}</div></div>
    <div class="stat"><div class="stat-label">Net Cashflow</div><div class="stat-value net">Rp {{ number_format($totalIncome-$totalExpense,0,',','.') }}</div></div>
</div>

<table>
    <thead><tr><th>Tanggal</th><th>Deskripsi</th><th>Kategori</th><th>Wallet</th><th>Tipe</th><th style="text-align:right">Jumlah</th></tr></thead>
    <tbody>
    @foreach($transactions as $tx)
    <tr>
        <td>{{ $tx->transaction_date->format('d M Y') }}</td>
        <td>{{ $tx->description ?? '—' }}</td>
        <td>{{ $tx->category?->name ?? '—' }}</td>
        <td>{{ $tx->wallet->name }}</td>
        <td>{{ ucfirst($tx->type) }}</td>
        <td style="text-align:right">Rp {{ number_format($tx->amount,0,',','.') }}</td>
    </tr>
    @endforeach
    </tbody>
</table>
<div class="footer">Generated by Finance AI · {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
